import = ["/home/miskyy/.config/alacritty/colors/tokyo-night.toml"]

[env]
WINIT_X11_SCALE_FACTOR = "1.0"

[font]
size = 11.5

[font.offset]
x = 0
y = -2

[font.bold]
family = "JetBrainsMonoNL Nerd Font Mono"
style = "Medium"

[font.bold_italic]
family = "JetBrainsMonoNL Nerd Font Mono"
style = "Medium Italic"

[font.italic]
family = "JetBrainsMonoNL Nerd Font Mono"
style = "Italic"

[font.normal]
family = "JetBrainsMonoNL Nerd Font Mono"
style = "Light"

[window]
decorations = "full"
dynamic_padding = true
#opacity = 0.88

[window.class]
general = "Alacritty"
instance = "Alacritty"

[window.padding]
x = 14
y = 14
